all:
	gcc -O0 overflow.c -o overflow -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/
	gcc -O0 variable.c -o variable -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/


clean:
	rm variable overflow
